- .editorconfig
- src/store.js
- src/tests/store.test.js
strings in particular caused "maximum call stack exceeded" errors because Object.keys('abc') returns an array of indexes to each character, which are in turn strings themselves
RKT-7629
> fix: handle non-object properties in environment config

- src/store.js
- src/tests/store.test.js
before: 
after: 
evolv.client.getActiveKeys() return key 'web', because there is no _predicate for this context, so no changes applied for it
Root case:
this bug was caused because of an incorrect check for active predicates. Function reevaluateContext did check in a loop if some string match regexp and added the active key to Map. The problem is that string can match regexp for one iteration and did not match for another, but it already added to Map as matched, so the solution is to combine all disabled contexts and do check with combined data.
> fix: fixed check for active contexts

- src/store.js
- src/tests/index.test.js
- src/tests/store.test.js
Loaded keys weren't experiment aware, this led to two experiments labeling each others keys as active in their active keys set. Which along with my previous change caused all treatments to render. This change makes loaded keys experiment aware so that experiments don't put keys that they don't own into their active set.
> fix: make loaded keys experiment aware

- src/index.js
- src/tests/index.test.js
The will maintain the current functionality, but when true is
passed to contaminate, it will send contaminations for all
eids into which the user is allocated.
> feat: RKT-8197 - Allow contaminations to be set of all eids

- src/ponyfills/arrays.js
- src/ponyfills/objects.js
- src/ponyfills/tests/arrays.test.js
- src/predicates.js
- src/retrieve.js
- src/store.js
- src/tests/store.test.js
Changing the client to read in predicated variants and correctly determine when to activate a predicated variant.
**Jira Ticket:** https://sentientai.atlassian.net/browse/RKT-7917
> feat: apply targeted variants

- src/retrieve.js
- src/tests/index.test.js
Currently, XHR requests are sync where they're meant to be async which can degrade performance. This commit negates to the "options.sync" parameter to align it to the XHR "async" argument.
> fix: AP-436 - Inverting sync value to match XHR API

- src/predicates.js
- src/tests/predicates.test.js
[Ticket](https://evolv-ai.atlassian.net/jira/software/c/projects/AP/boards/2?modal=detail&selectedIssue=AP-924)
Added handlers for new audience fields
Fix: **updated 'exists' handler.**
When tested noticed that even the field does not exist in **evolv.context.remoteContext** we are still in target and changes were applied. Added additional check that property is not **undefined** (before we checked that it is not **null** only)
@robertsevernsentient @tfoster Please confirm that I can make this change to the existing audience property handler
> feat(ap-924): add handlers for new audience props

- src/beacon.js
One of the test in asset-manager fails after using latest version of javascript-sdk. With this change we will fix this issue
> fix for asset manager tests

- src/build-options.js
- src/index.js
- src/retrieve.js
- src/store.js
- src/tests/index.test.js
The purpose of this change is allow users of the SDK to modify HTTP requests before they are sent out. The express need is so that the asset manager can append a `previewcid` query parameter.
I'm not 100% certain this is the best approach, so alternative approaches are welcome.
> feat(AP-773): support for request hooks

- package-lock.json
- package.json
- src/ponyfills/strings.js
- src/ponyfills/tests/strings.test.js
- src/store.js
- src/tests/index.test.js
- webpack.common.cjs
All repositories should use the same hashing module. JavaScript-SDK was using it's own.
> feat(ap-974): make `strings.hashCode` to use `hashing.objectHash`

- package.json
the bundle currently includes most of the files in the repo including build files and deployment scripts
> ci: restrict set of files included in package bundle

- .eslintrc.json
- package-lock.json
- package.json
- rollup.config.js
earlier entries have priority, so "node" was being ignored since "import" was listed earlier
> fix(AP-1778): reorder exports in package.json

- src/beacon.js
- src/tests/beacon.test.js
Without this limit, whenever the beacon fails, we become stuck in a loop where we throw errors in the console and crash the user's device.
> fix(ap-1844): added limit to analytic beacon retries.

- src/ponyfills/base64.js
package does not export a default and thus breaks downstream usages
> fix(AP-1778): fix import statement for base64-arraybuffer

- src/index.js
It duplicates the data going to analytics and is unused
> AP-1900 remove context from confirmation and contamination

- src/index.js
Add a promise for confirm method, so we can use it to understand if all confirmations have been sent.
Tested by using setTimeout instead of `waitFor` . See screenrecording:
https://user-images.githubusercontent.com/95315222/213318349-260dbdd8-497a-4806-a7f7-645cc8e6edc1.mov
> Add a promise for confirm

- src/store.js
- src/tests/store.test.js
This change allows the javascript SDK to resolve keys as "undefined", when not present in the genome but in the config. This will only change behavior when interacting with a version 1 participant endpoint.
> AP-2463: Resolving keys present in config, but not genome

- src/tests/time-context.test.js
- src/time-context.js
The audience builder uses the schema `path` to set the hierarchy. We don't support custom paths, so this needed updating.
> feat(AP-2109): Changed the path for each timer option

- src/beacon.js
- src/tests/beacon.test.js
- src/tests/index.test.js
GET requests are significantly cheaper than POSTs
Switch to fetch instead of beacon -- as beacon does not support get requests. Use keepalive to maintain the beacon functionality when a page is closed
Use visibilitychange as it is more reliable than before unload (https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon)
Fallback to xhr post on error OR call it immediately if the individual message size is too large
AP-3519
> AP-3519 use a get request to send data back 

- .github/workflows/license-check.yml
Remove the attempt at ignoring Evolv, and use the pip license checker report to print out
> chore: Improve the license check to report on the pip license checker outcomes

- src/index.js
- src/store.js
- src/tests/index.test.js
- src/tests/store.test.js
[AP-5710]
like the tin, it moves confirmations into confirmationsinternal for internal users. also adds testing for it. might need an update if the backend doesn't follow this change exactly 🤷 
[AP-5710]: https://evolv-ai.atlassian.net/browse/AP-5710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: move confirmations somewhere else when the user is internal
